spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enterprise_iam?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: joecos10496
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true